# Generated by Django 5.0.2 on 2024-04-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='nome',
        ),
        migrations.AddField(
            model_name='producao',
            name='nota',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producao',
            name='popularidade',
            field=models.IntegerField(default=0),
        ),
    ]
