# Generated by Django 5.0.2 on 2024-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0002_remove_producao_nome_producao_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='titulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
