# Generated by Django 5.0.2 on 2024-04-09 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho', '0005_producao_classificacao_producao_especificacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='titulo',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
