from enum import Enum


class Genero(Enum):
    ACTION = "Ação"
    ADULT = "Adulto"
    ADVENTURE = "Aventura"
    ANIMATION = "Animação"
    BIOGRAPHY = "Biografia"
    COMEDY = "Comédia"
    CRIME = "Crime"
    DOCUMENTARY = "Documentário"
    DRAMA = "Drama"
    DRAMEDY = "Dramédia"
    EDUCATIONAL = "Educacional"
    FAMILY = "Família"
    FANTASY = "Fantasia"
    HISTORY = "História"
    HORROR = "Terror"
    MUSICAL = "Musical"
    MYSTERY = "Mistério"
    NOIR = "Noir"
    PSYCHOLOGICAL = "Psicológico"
    ROMANCE = "Romance"
    SCIFI = "Ficção Científica"
    SPORT = "Esporte"
    SUPERHERO = "Super-herói"
    THRILLER = "Suspense"
    WAR = "Guerra"
    WESTERN = "Faroeste"
