from enum import Enum


class Genero(Enum):
    ACAO = 'Ação'
    ANIMACAO = 'Animação'
    ANIME = 'Anime'
    AVENTURA = 'Aventura'
    BIOGRAFIA = 'Biografia'
    COMEDIA = 'Comédia'
    CRIME = 'Crime'
    DOCUMENTARIO = 'Documentário'
    DRAMA = 'Drama'
    ESPORTE = 'Esporte'
    FANTASIA = 'Fantasia'
    FICCAO_CIENTIFICA = 'Ficção Científica'
    GUERRA = 'Guerra'
    HISTORIA = 'História'
    INFANTIL = 'Infantil'
    MAGIA = 'Magia'
    MISTERIO = 'Mistério'
    MUSICAL = 'Musical'
    NOIR = 'Noir'
    PARODIA = 'Paródia'
    POLICIAL = 'Policial'
    PSICOLOGICO = 'Psicológico'
    REALITY_SHOW = 'Reality Show'
    ROMANCE = 'Romance'
    SUSPENSE = 'Suspense'
    SUPERHEROI = 'Super-herói'
    TERROR = 'Terror'
    THRILLER = 'Thriller'
    WESTERN = 'Western'
